export const SOCKET_EVENTS: {
  readonly CONNECTION: 'connection';
  readonly CONNECT: 'connect';
  readonly DISCONNECT: 'disconnect';
  readonly ERROR: 'error';
  readonly CHECK_WORKSPACE_EXISTS: 'check-workspace-exists';
  readonly WORKSPACE_EXISTS_RESULT: 'workspace-exists-result';
  readonly JOIN_WORKSPACE: 'join-workspace';
  readonly LEAVE_WORKSPACE: 'leave-workspace';
  readonly USER_JOINED: 'user-joined';
  readonly USER_LEFT: 'user-left';
  readonly WORKSPACE_STATE: 'workspace-state';
  readonly WHITEBOARD_UPDATE: 'whiteboard-update';
  readonly WHITEBOARD_CLEAR: 'whiteboard-clear';
  readonly DELETE_ELEMENT: 'delete-element';
  readonly DELETE_DIAGRAM: 'delete-diagram';
  readonly DRAWING_START: 'drawing-start';
  readonly DRAWING_STREAM: 'drawing-stream';
  readonly DRAWING_END: 'drawing-end';
  readonly SHAPE_DRAWING_START: 'shape-drawing-start';
  readonly SHAPE_DRAWING_UPDATE: 'shape-drawing-update';
  readonly SHAPE_DRAWING_END: 'shape-drawing-end';
  readonly CODE_UPDATE: 'code-update';
  readonly DIAGRAM_UPDATE: 'diagram-update';
  readonly GET_SHARING_INFO: 'get-sharing-info';
  readonly SHARING_INFO: 'sharing-info';
  readonly SHARING_UPDATE: 'sharing-update';
  readonly GET_ACTIVE_USERS: 'get-active-users';
  readonly ACTIVE_USERS_UPDATE: 'active-users-update';
  readonly INVITE_USER: 'invite-user';
  readonly REQUEST_CANVAS_STATE: 'request-canvas-state';
  readonly CANVAS_STATE: 'canvas-state';
  readonly CURSOR_POSITION: 'cursor-position';
  readonly CURSOR_UPDATE: 'cursor-update';
  readonly GET_EDIT_TOKEN: 'get-edit-token';
  readonly SET_EDIT_TOKEN: 'set-edit-token';
  readonly EDIT_TOKEN_UPDATED: 'edit-token-updated';
  readonly END_SESSION: 'end-session';
  readonly SESSION_ENDED: 'session-ended';
  readonly CHANGE_SHARING_MODE: 'change-sharing-mode';
  readonly SHARING_MODE_CHANGED: 'sharing-mode-changed';
};

export const SHARING_MODES: {
  readonly READ_WRITE_ALL: 'read-write-all';
  readonly READ_ONLY: 'read-only';
  readonly READ_WRITE_SELECTED: 'read-write-selected';
};
